schema_name: "Peacekeeping Network"
schema_description: "2015年以降に展開された国連平和維持活動の主要拠点と専門部隊ネットワークを可視化します。"
attribution: "<a href=\"https://www.openstreetmap.org/copyright\" target=\"_blank\">&copy; OpenStreetMap contributors</a> | GeoPKO v2.3 (Uppsala Universitet)"

sources:
  osm:
    type: osm
    local_path: /osm_planet/planet-latest.osm.pbf

  natural_earth:
    type: geopackage
    url: "https://naciscdn.org/naturalearth/packages/natural_earth_vector.gpkg.zip"
    projection: EPSG:4326

  peacekeeping_sites:
    type: geojson
    local_path: /data/peacekeeping_network_sites.geojson

layers:
  - id: "land"
    features:
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }':
            - ne_110m_land
            - ne_50m_land
            - ne_10m_land
        min_zoom:
          10:
            '${ feature.source_layer }': [ ne_10m_land ]
          5:
            '${ feature.source_layer }': [ ne_50m_land ]
          0:
            '${ feature.source_layer }': [ ne_110m_land ]
        max_zoom:
          14:
            '${ feature.source_layer }': [ ne_10m_land ]
          9:
            '${ feature.source_layer }': [ ne_50m_land ]
          4:
            '${ feature.source_layer }': [ ne_110m_land ]

  - id: "ocean"
    features:
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }':
            - ne_110m_ocean
            - ne_50m_ocean
            - ne_10m_ocean
        min_zoom:
          10:
            '${ feature.source_layer }': [ ne_10m_ocean ]
          5:
            '${ feature.source_layer }': [ ne_50m_ocean ]
          0:
            '${ feature.source_layer }': [ ne_110m_ocean ]
        max_zoom:
          14:
            '${ feature.source_layer }': [ ne_10m_ocean ]
          9:
            '${ feature.source_layer }': [ ne_50m_ocean ]
          4:
            '${ feature.source_layer }': [ ne_110m_ocean ]

  - id: "peacekeeping_hq"
    features:
      - source: peacekeeping_sites
        geometry: point
        min_zoom: 0
        include_when:
          is_hq: true
        attributes:
          - key: mission
            value: '${ feature.tags.mission }'
          - key: location
            value: '${ feature.tags.location }'
          - key: country
            value: '${ feature.tags.country }'
          - key: reported_date
            value: '${ feature.tags.reported_date }'
          - key: troops
            value: '${ feature.tags.troops }'
          - key: tcc_count
            value: '${ feature.tags.tcc_count }'
          - key: specialized_units
            value: '${ feature.tags.specialized_units }'
          - key: contributors
            value: '${ feature.tags.contributors }'
          - key: deployment_scale
            value: '${ feature.tags.deployment_scale }'

  - id: "peacekeeping_deployments"
    features:
      - source: peacekeeping_sites
        geometry: point
        min_zoom: 1
        attributes:
          - key: mission
            value: '${ feature.tags.mission }'
          - key: location
            value: '${ feature.tags.location }'
          - key: country
            value: '${ feature.tags.country }'
          - key: reported_date
            value: '${ feature.tags.reported_date }'
          - key: troops
            value: '${ feature.tags.troops }'
          - key: tcc_count
            value: '${ feature.tags.tcc_count }'
          - key: is_hq
            value: '${ feature.tags.is_hq }'
          - key: has_unpol
            value: '${ feature.tags.has_unpol }'
          - key: has_unmo
            value: '${ feature.tags.has_unmo }'
          - key: contributors
            value: '${ feature.tags.contributors }'
          - key: specialized_units
            value: '${ feature.tags.specialized_units }'
          - key: deployment_scale
            value: '${ feature.tags.deployment_scale }'
