# Defines the layers for the Global Human Security Map.
# This theme provides a novel insight by overlaying environmental stress (water risk)
# with on-the-ground humanitarian/development responses (WASH infrastructure and UN Peacekeeping).

schema_name: "Global Human Security"
schema_description: "A map visualizing the intersection of water stress, WASH infrastructure, and UN peacekeeping missions."
attribution: "<a href=\"https://www.openstreetmap.org/copyright\" target=\"_blank\">&copy; OpenStreetMap contributors</a> | <a href=\"https://www.wri.org/\">WRI Aqueduct</a> | <a href=\"https://ucdp.uu.se/\">UCDP</a>"

sources:
  # Pre-processed Aqueduct 4.0 Water Risk data joined with HydroSHEDS basins
  water_stress:
    type: geojson
    local_path: /data/water_risk_basins.geojson

layers:
  # --- The Core Insight Layers ---
  # Layer 1: The Problem - Overall Water Risk (Visible at Zoom 0 for maximum impact)
  - id: "water_stress_areas"
    features:
      - source: water_stress
        geometry: polygon
        min_zoom: 0
        attributes:
          - key: water_risk
            value: '${ feature.tags.water_risk }'
            type: integer
