schema_name: "Debug Test"
schema_description: "A minimal theme to test the wdpa_2 shapefile in isolation."
attribution: "Internal Test"

args:
  minzoom: 0
  maxzoom: 10

sources:
  wdpa_2:
    type: shapefile
    local_path: /data/WDPA_polygons_2.shp

layers:
  - id: "protected_areas_test"
    features:
      - source: wdpa_2
        geometry: polygon