schema_name: Debug Test
schema_description: A minimal theme for testing with only land and ocean.
attribution: "Natural Earth"

sources:
  natural_earth:
    type: shapefile
    url: https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_land.zip
  ocean:
    type: shapefile
    url: https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_ocean.zip

layers:
  - id: "land"
    features:
      - source: natural_earth
        geometry: polygon
  - id: "ocean"
    features:
      - source: ocean
        geometry: polygon
