schema_name: Global Healthcare Access
schema_description: "Visualizes global healthcare access, highlighting facility types, emergency services, and specializations. (z0-14)"
attribution: '<a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>, <a href="http://www.naturalearthdata.com/" target="_blank">Natural Earth</a>'

sources:
  # Natural Earth for base layers and country context
  natural_earth:
    type: geopackage
    url: "https://naciscdn.org/naturalearth/packages/natural_earth_vector.gpkg.zip"
    projection: EPSG:4326
  # OpenStreetMap for detailed healthcare facility data
  osm:
    type: osm
    local_path: /data/planet-latest.osm.pbf

layers:
  # --- Base Layers from Natural Earth ---
  - id: ocean
    features:
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_110m_ocean
        min_zoom: 0
        max_zoom: 4
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_50m_ocean
        min_zoom: 5
        max_zoom: 9
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_10m_ocean
        min_zoom: 10
        max_zoom: 14

  - id: land
    features:
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_110m_land
        min_zoom: 0
        max_zoom: 4
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_50m_land
        min_zoom: 5
        max_zoom: 9
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_10m_land
        min_zoom: 10
        max_zoom: 14

  - id: lakes
    features:
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_110m_lakes
        min_zoom: 0
        max_zoom: 4
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_50m_lakes
        min_zoom: 5
        max_zoom: 9
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_10m_lakes
        min_zoom: 10
        max_zoom: 14

  - id: countries
    features:
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_110m_admin_0_countries
        min_zoom: 0
        max_zoom: 4
        attributes:
          - key: name
            value: '${ feature.tags.NAME }'

  # --- Healthcare Layer from OSM ---
  - id: healthcare
    features:
      # Points for various facilities
      - source: osm
        geometry: point
        include_when:
          or:
            - amenity: [ hospital, clinic, doctors, dentist, pharmacy, health_post ]
            - healthcare: __any__
        min_zoom: 6
        attributes:
          - key: name
            value: '${ feature.tags.name }'
          - key: operator
            value: '${ feature.tags.operator }'
          - key: class
            type: string
            value:
              match:
                - value: hospital
                  if: { amenity: hospital }
                - value: hospital
                  if: { healthcare: hospital }
                - value: clinic
                  if: { amenity: [ clinic, doctors, health_post ] }
                - value: clinic
                  if: { healthcare: [ clinic, doctor, health_post ] }
                - value: pharmacy
                  if: { amenity: pharmacy }
                - value: pharmacy
                  if: { healthcare: pharmacy }
                - value: dentist
                  if: { amenity: dentist }
                - value: dentist
                  if: { healthcare: dentist }
                - else: unknown
          - key: emergency
            type: boolean
            value:
              match:
                - value: true
                  if: { emergency: yes }
                - else: false
          - key: beds
            value: '${ feature.tags["capacity:beds"] }'
          - key: speciality
            value: '${ feature.tags["healthcare:speciality"] }'
      # Polygons for hospital areas
      - source: osm
        geometry: polygon
        include_when:
          amenity: hospital
        min_zoom: 10
        attributes:
          - key: name
            value: '${ feature.tags.name }'
          - key: class
            value: hospital
          - key: emergency
            type: boolean
            value:
              match:
                - value: true
                  if: { emergency: yes }
                - else: false
          - key: beds
            value: '${ feature.tags["capacity:beds"] }'
          - key: speciality
            value: '${ feature.tags["healthcare:speciality"] }'
