schema_name: Global Healthcare Access
schema_description: "Visualizes global healthcare access, highlighting facility types, emergency services, and specializations. (z0-14)"
attribution: '<a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>, <a href="http://www.naturalearthdata.com/" target="_blank">Natural Earth</a>'

sources:
  # Natural Earth for base layers and country context
  natural_earth:
    type: geopackage
    url: "https://naciscdn.org/naturalearth/packages/natural_earth_vector.gpkg.zip"
    projection: EPSG:4326
  # OpenStreetMap for detailed healthcare facility data
  osm:
    type: osm
    local_path: /data/planet-latest.osm.pbf

layers:
  # --- Base Layers from Natural Earth ---
  - id: ocean
    features:
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_110m_ocean
        min_zoom: 0
        max_zoom: 4
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_50m_ocean
        min_zoom: 5
        max_zoom: 9
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_10m_ocean
        min_zoom: 10
        max_zoom: 14

  - id: land
    features:
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_110m_land
        min_zoom: 0
        max_zoom: 4
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_50m_land
        min_zoom: 5
        max_zoom: 9
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_10m_land
        min_zoom: 10
        max_zoom: 14

  - id: lakes
    features:
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_110m_lakes
        min_zoom: 0
        max_zoom: 4
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_50m_lakes
        min_zoom: 5
        max_zoom: 9
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_10m_lakes
        min_zoom: 10
        max_zoom: 14

  - id: countries
    features:
      - source: natural_earth
        geometry: polygon
        include_when:
          '${ feature.source_layer }': ne_110m_admin_0_countries
        min_zoom: 0
        max_zoom: 4
        attributes:
          - key: name
            value: '${ feature.tags.NAME }'

  # --- Healthcare Layer from OSM ---
  # This single layer consolidates all healthcare-related features for efficiency and clear styling.
  - id: healthcare
    features:
      # Points for various facilities
      - source: osm
        geometry: point
        # Include all relevant amenities and healthcare tags
        include_when:
          or:
            - amenity: [ hospital, clinic, doctors, dentist, pharmacy, health_post ]
            - healthcare: [ hospital, clinic, doctor, dentist, pharmacy, health_post ]
        min_zoom: 6 # Start showing major facilities at a global level
        attributes:
          # --- Core Attributes ---
          - key: name
            value: '${ feature.tags.name }'
          - key: operator
            value: '${ feature.tags.operator }'
          # --- Standardized Class ---
          - key: class
            value:
              coalesce:
                - case:
                    when: "'${ feature.tags.amenity }' == 'hospital' || '${ feature.tags.healthcare }' == 'hospital'"
                    then: hospital
                - case:
                    when: "'${ feature.tags.amenity }' in ['clinic', 'doctors', 'health_post'] || '${ feature.tags.healthcare }' in ['clinic', 'doctor', 'health_post']"
                    then: clinic
                - case:
                    when: "'${ feature.tags.amenity }' == 'pharmacy' || '${ feature.tags.healthcare }' == 'pharmacy'"
                    then: pharmacy
                - case:
                    when: "'${ feature.tags.amenity }' == 'dentist' || '${ feature.tags.healthcare }' == 'dentist'"
                    then: dentist
          # --- Key Indicators ---
          - key: emergency
            value:
              case:
                when:
                  "'${ feature.tags.emergency }'": yes
                then: true
                else: false
          - key: beds
            value: "${ feature.tags['capacity:beds'] }"
          - key: speciality
            value: "${ feature.tags['healthcare:speciality'] }"
      # Polygons for hospital areas
      - source: osm
        geometry: polygon
        include_when:
          or:
            - amenity: hospital
            - healthcare: hospital
        min_zoom: 10
        attributes:
          - key: name
            value: '${ feature.tags.name }'
          - key: class
            value: hospital
          - key: emergency
            value:
              case:
                when:
                  "'${ feature.tags.emergency }'": yes
                then: true
                else: false
          - key: beds
            value: "${ feature.tags['capacity:beds'] }"
          - key: speciality
            value: "${ feature.tags['healthcare:speciality'] }"